#!/bin/bash
java -ea SubwayDriver  < test_input/small101 | diff - test_output/small101
java -ea SubwayDriver  < test_input/small102 | diff - test_output/small102
java -ea SubwayDriver  < test_input/small103 | diff - test_output/small103
java -ea SubwayDriver  < test_input/small104 | diff - test_output/small104
java -ea SubwayDriver  < test_input/small105 | diff - test_output/small105
java -ea SubwayDriver  < test_input/small106 | diff - test_output/small106
java -ea SubwayDriver  < test_input/small107 | diff - test_output/small107
java -ea SubwayDriver  < test_input/small108 | diff - test_output/small108
java -ea SubwayDriver  < test_input/small109 | diff - test_output/small109
java -ea SubwayDriver  < test_input/small110 | diff - test_output/small110
java -ea SubwayDriver  < test_input/small111 | diff - test_output/small111
java -ea SubwayDriver  < test_input/small112 | diff - test_output/small112
java -ea SubwayDriver  < test_input/small113 | diff - test_output/small113
java -ea SubwayDriver  < test_input/small114 | diff - test_output/small114
java -ea SubwayDriver  < test_input/small115 | diff - test_output/small115
java -ea SubwayDriver  < test_input/small116 | diff - test_output/small116
java -ea SubwayDriver  < test_input/small117 | diff - test_output/small117
java -ea SubwayDriver  < test_input/small118 | diff - test_output/small118
java -ea SubwayDriver  < test_input/small119 | diff - test_output/small119
java -ea SubwayDriver  < test_input/small120 | diff - test_output/small120
java -ea SubwayDriver  < test_input/small121 | diff - test_output/small121
java -ea SubwayDriver  < test_input/small122 | diff - test_output/small122
java -ea SubwayDriver  < test_input/small123 | diff - test_output/small123
java -ea SubwayDriver  < test_input/small124 | diff - test_output/small124
java -ea SubwayDriver  < test_input/small125 | diff - test_output/small125
java -ea SubwayDriver  < test_input/small126 | diff - test_output/small126
java -ea SubwayDriver  < test_input/small127 | diff - test_output/small127
java -ea SubwayDriver  < test_input/small128 | diff - test_output/small128
java -ea SubwayDriver  < test_input/small129 | diff - test_output/small129
java -ea SubwayDriver  < test_input/small130 | diff - test_output/small130
java -ea SubwayDriver  < test_input/small131 | diff - test_output/small131
java -ea SubwayDriver  < test_input/small132 | diff - test_output/small132
java -ea SubwayDriver  < test_input/small133 | diff - test_output/small133
java -ea SubwayDriver  < test_input/small134 | diff - test_output/small134
java -ea SubwayDriver  < test_input/small135 | diff - test_output/small135
java -ea SubwayDriver  < test_input/small136 | diff - test_output/small136
java -ea SubwayDriver  < test_input/small137 | diff - test_output/small137
java -ea SubwayDriver  < test_input/small138 | diff - test_output/small138
java -ea SubwayDriver  < test_input/small139 | diff - test_output/small139
java -ea SubwayDriver  < test_input/small140 | diff - test_output/small140
java -ea SubwayDriver  < test_input/small141 | diff - test_output/small141
java -ea SubwayDriver  < test_input/small142 | diff - test_output/small142
java -ea SubwayDriver  < test_input/small143 | diff - test_output/small143
java -ea SubwayDriver  < test_input/small144 | diff - test_output/small144
java -ea SubwayDriver  < test_input/small145 | diff - test_output/small145
java -ea SubwayDriver  < test_input/small146 | diff - test_output/small146
java -ea SubwayDriver  < test_input/small147 | diff - test_output/small147
java -ea SubwayDriver  < test_input/small148 | diff - test_output/small148
java -ea SubwayDriver  < test_input/small149 | diff - test_output/small149
java -ea SubwayDriver  < test_input/small150 | diff - test_output/small150
java -ea SubwayDriver  < test_input/small151 | diff - test_output/small151
java -ea SubwayDriver  < test_input/small152 | diff - test_output/small152
java -ea SubwayDriver  < test_input/small153 | diff - test_output/small153
java -ea SubwayDriver  < test_input/small154 | diff - test_output/small154
java -ea SubwayDriver  < test_input/small155 | diff - test_output/small155
java -ea SubwayDriver  < test_input/small156 | diff - test_output/small156
java -ea SubwayDriver  < test_input/small157 | diff - test_output/small157
java -ea SubwayDriver  < test_input/small158 | diff - test_output/small158
java -ea SubwayDriver  < test_input/small159 | diff - test_output/small159
java -ea SubwayDriver  < test_input/small160 | diff - test_output/small160
java -ea SubwayDriver  < test_input/small161 | diff - test_output/small161
java -ea SubwayDriver  < test_input/small162 | diff - test_output/small162
java -ea SubwayDriver  < test_input/small163 | diff - test_output/small163
java -ea SubwayDriver  < test_input/small164 | diff - test_output/small164
java -ea SubwayDriver  < test_input/small165 | diff - test_output/small165
java -ea SubwayDriver  < test_input/small166 | diff - test_output/small166
java -ea SubwayDriver  < test_input/small167 | diff - test_output/small167
java -ea SubwayDriver  < test_input/small168 | diff - test_output/small168
java -ea SubwayDriver  < test_input/small169 | diff - test_output/small169
java -ea SubwayDriver  < test_input/small170 | diff - test_output/small170
java -ea SubwayDriver  < test_input/small171 | diff - test_output/small171
java -ea SubwayDriver  < test_input/small172 | diff - test_output/small172
